config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "jobs#index"

  resources :printers
  resources :filaments
  resources :jobs, except: [:edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/filament.rb
class Filament < ApplicationRecord
  validates_presence_of :color, :brand, :full_weight, :material
end

app/models/job.rb
class Job < ApplicationRecord
  validates_presence_of :filament_id, :used_weight, :printer_id, :reference, :duration_mins 
end

app/models/print_job.rb
class PrintJob < ApplicationRecord
  validates_presence_of :filament_id, :usedWeight, :doneTime, :printer_id, :reference
end

app/models/printer.rb
class Printer < ApplicationRecord
  validates_presence_of :name, :startup_cost
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/filaments_controller.rb
class FilamentsController < ApplicationController
  #app/controllers/filaments_controller.rb
  skip_before_action :verify_authenticity_token
  before_action :find_filament, only: [:edit, :update, :show, :destroy]

  # Index action to render all filaments
  def index
    @filaments = Filament.all
  end

  # New action for creating filament
  def new
    @filament = Filament.new
  end

  # Create action saves the filament into database
  def create
    @filament = Filament.new(filament_params)
    if @filament.save
      flash[:notice] = "Successfully created filament!"
      redirect_to jobs_path
    else
      flash[:alert] = "Error creating new filament!"
      render :new
    end
  end

  # Edit action retrives the filament and renders the edit page
  def edit
  end

  # Update action updates the filament with the new information
  def update
    if @filament.update_attributes(filament_params)
      flash[:notice] = "Successfully updated filament!"
      redirect_to jobs_path
    else
      flash[:alert] = "Error updating filament!"
      render :edit
    end
  end

  # The show action renders the individual filament after retrieving the the id
  def show
  end

  # The destroy action removes the filament permanently from the database
  def destroy
    if @filament.destroy
      flash[:notice] = "Successfully deleted filament!"
      redirect_to jobs_path
    else
      flash[:alert] = "Error updating filament!"
    end
  end

  private

  def filament_params
    params.require(:filament).permit(:color, :brand, :full_weight, :material)
  end

  def find_filament
    @filament = Filament.find(params[:id])
  end
end

app/controllers/jobs_controller.rb
# `require 'json'

class JobsController < ApplicationController
  #app/controllers/jobs_controller.rb
  skip_before_action :verify_authenticity_token
  before_action :find_job, only: [:edit, :update, :show, :destroy]

  # Index action to render all print jobs
  def index
    @jobs = Job.all
  end

  # New action for creating print job
  def new
    @job = Job.new
  end

  # Create action saves the print job into database
  def create
    # render json: params
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = "Successfully created print job!"
      puts('JOB: ' + @job.to_json())
      redirect_to jobs_path
    else
      flash[:alert] = "Error creating new print job!"
      render :new
    end
  end

  # Edit action retrives the print job and renders the edit page
  def edit
  end

  # Update action updates the print job with the new information
  def update
    if @job.update_attributes(job_params)
      flash[:notice] = "Successfully updated print job!"
      redirect_to jobs_path
    else
      flash[:alert] = "Error updating print job!"
      render :edit
    end
  end

  # The show action renders the individual print job after retrieving the the id
  def show
  end

  # The destroy action removes the print job permanently from the database
  def destroy
    if @job.destroy
      flash[:notice] = "Successfully deleted print job!"
    else
      flash[:alert] = "Error updating print job!"
    end
  end

  private

  def job_params
    params.require(:job).permit(:filament_id, :used_weight, :duration_mins, :printer_id, :reference)
  end

  def find_job
    @job = Job.find(params[:id])
  end
end

app/controllers/print_jobs_controller.rb
class PrintJobsController < ApplicationController
  #app/controllers/print_jobs_controller.rb
  skip_before_action :verify_authenticity_token
  before_action :find_print_job, only: [:edit, :update, :show, :destroy]

  # Index action to render all print jobs
  def index
    @print_jobs = PrintJob.all
  end

  # New action for creating print job
  def new
    @print_job = PrintJob.new
  end

  # Create action saves the print job into database
  def create
    @print_job = PrintJob.new(print_job_params)
    if @print_job.save
      flash[:notice] = "Successfully created print job!"
      redirect_to @print_job 
    else
      flash[:alert] = "Error creating new print job!"
      render :new
    end
  end

  # Edit action retrives the print job and renders the edit page
  def edit
  end

  # Update action updates the print job with the new information
  def update
    if @print_job.update_attributes(print_job_params)
      flash[:notice] = "Successfully updated print job!"
      redirect_to @print_job
    else
      flash[:alert] = "Error updating print job!"
      render :edit
    end
  end

  # The show action renders the individual print job after retrieving the the id
  def show
  end

  # The destroy action removes the print job permanently from the database
  def destroy
    if @print_job.destroy
      flash[:notice] = "Successfully deleted print job!"
    else
      flash[:alert] = "Error updating print job!"
    end
  end

  private

  def print_job_params
    params.require(:print_job).permit(:filament_id, :usedWeight, :doneTime, :printer_id, :reference)
  end

  def find_print_job
    @print_job = PrintJob.find(params[:id])
  end
end

app/controllers/printers_controller.rb
class PrintersController < ApplicationController
	#app/controllers/printers_controller.rb
  skip_before_action :verify_authenticity_token
  before_action :find_printer, only: [:edit, :update, :show, :destroy]

  # Index action to render all printers
  def index
    @printers = Printer.all
  end

  # New action for creating printer
  def new
    @printer = Printer.new
  end

  # Create action saves the printer into database
  def create
    @printer = Printer.new(printer_params)
    if @printer.save
      flash[:notice] = "Successfully created printer!"
      redirect_to jobs_path
    else
      flash[:alert] = "Error creating new printer!"
      render :new
    end
  end

  # Edit action retrives the printer and renders the edit page
  def edit
  end

  # Update action updates the printer with the new information
  def update
    if @printer.update_attributes(printer_params)
      flash[:notice] = "Successfully updated printer!"
      redirect_to jobs_path
    else
      flash[:alert] = "Error updating printer!"
      render :edit
    end
  end

  # The show action renders the individual printer after retrieving the the id
  def show
  end

  # The destroy action removes the printer permanently from the database
  def destroy
    if @printer.destroy
      flash[:notice] = "Successfully deleted printer!"
    else
      flash[:alert] = "Error updating printer!"
    end
  end

  private

  def printer_params
    params.require(:printer).permit(:name, :startup_cost)
  end

  def find_printer
    @printer = Printer.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filaments_helper.rb
module FilamentsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/printers_helper.rb
module PrintersHelper
end

app/views/filaments/_embed_index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-9"><h5 class="header-with-icon">My Filaments</h5></div>
    <div class="col-3"><%= link_to raw("<i class=\"fa fa-2x fa-plus-circle\" aria-hidden=\"true\"></i>"), new_filament_path, method: :get, class:"icon-btn"  %></div>
  </div>
</div>
<div class="container first-section">
  <% if Filament.all.length == 0  %>
    <div class="center-notice">
      <h4>No filaments found</h4>
      <p>Studies have shown that printing using material leads to better results.</p>
    </div>
  <% end %>

  <% Filament.all.each do |filament| %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-8">
          <h6><%= filament.brand %> <%= filament.material %> (<%= filament.color %>)</h6>
          <p>Spool size: <%= filament.full_weight %> kg</p>
          <p class="sub-info">Added <%= filament.created_at.strftime('%H:%M | %b %d, %Y') %></p>
        </div>
        <div class="col-4 center-vertical">
          <div class="tight-hover-btns">
            <%= link_to raw("<i class=\"fa fa-pencil-alt\" aria-hidden=\"true\"></i>"), { action: "edit", :controller => "filaments", id: filament.id }, method: :get, class: "btn btn-outline-info" %>
            <%= link_to raw("<i class=\"far fa-trash-alt\" aria-hidden=\"true\"></i>"), { action: "destroy", :controller => "filaments", id: filament.id }, method: :delete, class: "btn btn-outline-danger" %>
          </div>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/filaments/_embed_new.html.erb
<h5 style="margin-bottom:1em;">Add New Filament</h5>

<%= render "filaments/form" %>

app/views/filaments/_form.html.erb
<div class="container">
  <%= form_for @filament do |f| %>
    <div class="row">
      <div class="col-2 form-label">
        <%= f.label(:material, 'Material') %>
        <br>
        <%= f.label :color %>
        <br>
        <%= f.label :brand %>
        <br>
        <%= f.label(:full_weight, 'Spool size (kg)') %>
        <br>
      </div>
      <div class="col-2 form-inputs">
        <%= f.text_field :material %>
        <br>
        <%= f.text_field :color %>
        <br>
        <%= f.text_field :brand %>
        <br>
        <%= f.number_field :full_weight, :value => 1, :step => :any %>
        <br>
      </div>
    </div>

    <%= f.submit "Submit", class: "submit-btn" %>
  <% end %>
</div>

app/views/filaments/edit.html.erb
<h1>Edit Filament</h1>

<%= render "filaments/form" %>

app/views/filaments/index.html.erb
<h3>All Filaments</h3>
<div class="container">
  <% @filaments.each do |filament| %>
    <h4>ID <%= filament.id %></h4>

    <h6>Type: <%= filament.material %></h6>
    <h6>Color: <%= filament.color %></h6>
    <h6>Brand: <%= filament.brand %></h6>
    <h6>Spool size: <%= filament.fullWeight %></h6>
    <h6>Added: <%= filament.created_at.strftime('%H:%M | %b %d, %Y') %></h6>
    <hr>
  <% end %>
</div>

app/views/filaments/new.html.erb
<h5 style="margin-bottom:1em;">Add New Filament</h5>

<%= render "filaments/form" %>

app/views/filaments/show.html.erb
<h1>Filament</h1><p> number <%= @filament.id %></p>

<h4>Type: <%= @filament.material %></h4>
<h4>Color: <%= @filament.color %></h4>
<h4>Brand: <%= @filament.brand %></h4>
<h4>Spool size: <%= @filament.full_weight %>kg</h4>
<h4>Added: <%= @filament.created_at.strftime('%H:%M | %b %d, %Y') %></h4>

app/views/jobs/_form.html.erb
<div class="container">
  <%= form_for @job do |j| %>
    <div class="row">
      <div class="col-2 form-label">
        <%= j.label(:filament_id, 'Filament') %>
        <br>
        <%= j.label(:used_weight, 'Weight Used (g)') %>
        <br>
        <%= j.label(:printer_id, 'Printer') %>
        <br>
        <%= j.label(:reference, 'Reference') %>
        <br>
        <%= j.label(:duration_mins, 'Duration (mins)') %>
        <br>
      </div>
      <div class="col-2 form-inputs">
        <%= j.select(:filament_id, options_for_select(Filament.all.map { |f| [f.brand + ' - ' + f.material + ' - ' + f.color, f.id] }, @job.filament_id), {include_blank: "Select filament"}) %>
        <br>
        <%= j.number_field :used_weight, :step => :any %>
        <br>
        <%= j.select(:printer_id, options_for_select(Printer.all.map { |p| [p.name, p.id] }, @job.printer_id), {include_blank: "Select printer"}) %>
        <br>
        <%= j.text_field :reference %>
        <br>
        <%= j.number_field :duration_mins, :value => 1 %>
        <br>
      </div>
    </div>

    <%= j.submit "Submit", class: "submit-btn" %>
  <% end %>
</div>

app/views/jobs/edit.html.erb
<h1>Edit Print Job</h1>
<div class="alert alert-danger" role="alert">
  This is an unsupported feature, and there are probably some bugs in this action!
</div>

<%= render "jobs/form" %>

app/views/jobs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8">
      <div class="container-fluid">
        <div class="row">
          <div class="col-9"><h3>Print Jobs</h3></div>
          <div class="col-3"><div><%= button_to "Add Job", { action: "new" }, method: :get, class:"btn btn-primary", style:"float:right;" %></div></div>
        </div>
      </div>

      <div class="container" style="margin-top:1em;">
        <% if @jobs.length == 0  %>
          <div class="center-notice">
            <h4>Getting lazy, ay?</h4>
            <p>Go get something printing!</p>
          </div>
        <% end %>

        <% @jobs.each do |job| %>
          <div class="row">
            <div class="col-8 body">
              <div class="container-fluid">
                <div class="row">
                  <div class="col-4" style="text-align:right;color:gray;">
                    <p>Filament</p>
                    <p>Weight</p>
                    <p>Printer</p>
                    <p>Reference</p>
                    <p>Duration</p>
                    <p>Created</p>
                  </div>
                  <div class="col-8">
                    <p><%= Filament.find(job.filament_id).brand + ' ' +  Filament.find(job.filament_id).material + ' (' +  Filament.find(job.filament_id).color + ')' %></p>
                    <p><%= number_with_precision(job.used_weight, :precision => 3) %> g</p>
                    <p><%= Printer.find(job.printer_id).name %></p>
                    <p><%= job.reference %></p>
                    <p><%= job.duration_mins %> mins</p>
                    <p><%= job.created_at.strftime('%H:%M | %b %d, %Y') %></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-4">
              <div class="hover-btns job-btns">
                <div><%= link_to raw("<i class=\"far fa-trash-alt\" aria-hidden=\"true\"></i>"), { action: "destroy", id: job.id }, method: :delete, class: "btn btn-danger" %></div>
              </div>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>

    <div class="col-4">
      <%= render "filaments/embed_index" %>
      <%= render "printers/embed_index" %>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<h1>Print Job</h1><p>ID - <%= @job.id %></p>

<h4>Filament: <%= Filament.find(@job.filament_id).brand + ' ' +  Filament.find(@job.filament_id).material + ' (' +  Filament.find(@job.filament_id).color + ')' %> </h4>
<h4>Weight: <%= number_with_precision(@job.used_weight) %>g</h4>
<h4>Printer: <%= Printer.find(@job.printer_id).name %> </h4>
<h4>Reference: <%= @job.reference %> </h4>
<h4>Completed: <%= @job.duration_mins %> </h4>
<h4>Created: <%= @job.created_at.strftime('%b %d, %Y') %> </h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manage Prints</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Font Awesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.2/js/all.js"></script>
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Arvo|Patua+One" rel="stylesheet">
  </head>

  <body>
    <div class="container" style="margin-top:2em;">
      <div class="header">
        <h1 style="margin-right:0.25em;">3D Printing Manager</h1>
        <h6>by TIKA</h6>
        <hr>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/printers/_embed_index.html.erb
<div class="container-fluid first-heading">
  <div class="row">
    <div class="col-9 center-vertical"><h5 class="header-with-icon">Active Printers</h5></div>
    <div class="col-3"><%= link_to raw("<i class=\"fa fa-2x fa-plus-circle\" aria-hidden=\"true\"></i>"), new_printer_path, method: :get, class:"icon-btn"  %></div>
  </div>
</div>
<div class="container first-section">
  <% if Printer.all.length == 0  %>
    <div class="center-notice">
      <h4>No printers found</h4>
      <p>2D is so 2000's. Add a 3D printer!</p>
    </div>
  <% end %>

  <% Printer.all.each do |printer| %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-8">
          <h6><%= printer.name %></h6>
          <h6>Startup Cost: $<%= number_with_precision(printer.startup_cost, :precision => 2) %></h6>
          <h6>Created: <%= printer.created_at.strftime('%b %d, %Y') %></h6>
        </div>
        <div class="col-4 center-vertical">
          <div class="tight-hover-btns">
            <%= link_to raw("<i class=\"fa fa-pencil-alt\" aria-hidden=\"true\"></i>"), { action: "edit", :controller => "printers", id: printer.id }, method: :get, class: "btn btn-outline-info" %>
            <%= link_to raw("<i class=\"far fa-trash-alt\" aria-hidden=\"true\"></i>"), { action: "destroy", :controller => "printers", id: printer.id }, method: :delete, class: "btn btn-outline-danger" %>
          </div>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/printers/_form.html.erb
<div class="container">
  <%= form_for @printer do |p| %>
    <div class="row">
      <div class="col-2 form-label">
        <%= p.label :name %>
        <br>
        <%= p.label(:startup_cost, 'Startup Cost') %>
        <br>
      </div>
      <div class="col-2 form-inputs">
        <%= p.text_field :name %>
        <br>
        <%= p.number_field :startup_cost, value: number_to_currency(p.object.startup_cost.to_f, delimiter: '', unit: ''), step: :any %>
        <br>
      </div>
    </div>

    <%= p.submit "Submit", class: "submit-btn" %>
  <% end %>
</div>

app/views/printers/edit.html.erb
<h5 style="margin-bottom:1em;">Edit Printer</h5>

<%= render "printers/form" %>

app/views/printers/index.html.erb
<h3 style="margin-top:1em;">Active printers</h3>
<div class="container">
  <% @printers.each do |printer| %>
    <h4>ID <%= printer.id %></h4>

    <h6>Name: <%= printer.name %></h6>
    <h6>Startup Cost: $<%= number_with_precision(printer.startupCost, :precision => 2) %></h6>
    <h6>Created: <%= printer.created_at.strftime('%b %d, %Y') %></h6>
    <hr>
  <% end %>
</div>

app/views/printers/new.html.erb
<h5 style="margin-bottom:1em;">Add a Printer</h5>

<%= render "printers/form" %>

app/views/printers/show.html.erb
<h1>Printer</h1><p> number <%= @printer.id %></p>

<h4>Name: <%= @printer.name %></h4>
<h4>Startup Cost: $<%= number_with_precision(@printer.startup_cost, :precision => 2) %></h4>
<h4>Created: <%= @printer.created_at.strftime('%b %d, %Y') %></h4>